<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\GymTest.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\Commons\" />
  </ItemGroup>

</Project>
