<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymTest.Application\GymTest.Application.csproj" />
    <ProjectReference Include="..\GymTest.Domain\GymTest.Domain.csproj" />
  </ItemGroup>

</Project>
